language: java
env: MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m" GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=192m" TERM="dumb"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
sudo: false
script:
  - './gradlew clean build && groovy testbuild.groovy -gradle && make TAG=SNAPSHOT BUILD_NUM=$TRAVIS_BUILD_NUMBER rpm deb'
addons:
  apt:
    packages:
    - groovy
    - rpm
    - make
    - zip
    - unzip
# whitelist
branches:
  only:
    - development

notifications:
  irc:
    - "irc.freenode.org#rundeck"
  #email: false


