language: java
script: mvn -q clean install
env: MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"

# whitelist
branches:
  only:
    - development

notifications:
  irc:
    - "irc.freenode.org#rundeck"
  #email: false


